### ISSUE TITLE
Newbie questions!

### ISSUE THREAD

**Issue by antdude** [Zarthus/irc-pokemon-go-status#3]
What are the command for this IRC Pokemon Go Status bot? I tried help, but got nothing.

Thank you in advance. :)

**Comment by Zarthus** [comment]
There's only `!gostatus`, the bot announces by itself except I turned off `@reporting` due to flood. Turn it on by changing https://github.com/Zarthus/irc-pokemon-go-status/blob/master/lib/gobot/plugins/go_status.rb#L15 from false to true

Right now though  it appears to only check for the login servers, and MMOStatus captures all servers.

Referencing to http://www.mmoserverstatus.com/pokemon_go would be more accurate

**Comment by antdude** [comment]
Ah thanks. Yeah, I never saw any announcements. I tried gostatus command, but nothing:
...

```
[10:23am] <Ant> DurANT gostatus
[10:23am] <Ant> DurANT ogostatus
[10:23am] <Ant> DurANT o gostatus
[10:23am] <Ant> hmm
[10:23am] <Ant> !gostatus
[msg(DurANT)] gostatus
```

...

$ pwd
/home/ant/bin/irc-pokemon-go-status/conf
$ cat config.yml

``` yml
irc:
  server: "irc.[deleted].net"
  server_password:
  port: 6697
  ssl: true
  ssl_verify: false
  bind:
  umodes:

  realname: "Pokémon Go Status Bot"
  username: "PokemonGoStatusBot"
  nick: "DurANT"

  auth:
    cert:
      client_cert:

    sasl:
      account:
      password:

  channels:
    - "#bots,#linux"

logging: true
prefix: "o"
source_url: "https://github.com/zarthus/irc-pokemon-go-status"
```
